### PR TITLE
fix: return http protocol if the proxy is untrusted

### LINKED ISSUE #8: Bug in protocol() method
If `trustProxy` returns false, the `protocol()` method always returns `null`.

The reason is that the following line actually will never return a string, because IncomingMessage.url doesn't contain information about the protocol/hostname/port. [It only has the path part](https://nodejs.org/dist/latest-v12.x/docs/api/http.html#http_message_url)
https://github.com/poppinss/request/blob/9eaac0f55997db980c9254ce1fe6e4de84bb1722/src/Request.ts#L416

Here's a test case showing the issue:
```diff
diff --git a/test/request.spec.ts b/test/request.spec.ts
index cce62c0..4f6b22b 100644
--- a/test/request.spec.ts
+++ b/test/request.spec.ts
@@ -299,6 +299,22 @@ test.group('Request', () => {
     })
   })

+  test('get request protocol without trusting proxy', async (assert) => {
+    const server = createServer((req, res) => {
+      const config = fakeConfig()
+      config.trustProxy = () => false
+      const request = new Request(req, res, config)
+
+        res.writeHead(200, { 'content-type': 'application/json' })
+        res.end(JSON.stringify({ protocol: request.protocol() }))
+      })
+
+      const { body } = await supertest(server).get('/')
+      assert.deepEqual(body, {
+        protocol: 'http',
+      })
+  })
+
   test('get boolean telling request is secure or not', async (assert) => {
     const server = createServer((req, res) => {
       const request = new Request(req, res, fakeConfig())
```

```
Request

  ✖ get request protocol without trusting proxy
    Assertion Error: expected { protocol: null } to deeply equal { protocol: 'http' }
    {
      protocol: null => "http"
    }
```

### PR DESCRIPTION
**Pull request by targos**
Fixes: https://github.com/poppinss/request/issues/8

## Types of changes

What types of changes does your code introduce?

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/poppinss/request/blob/master/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: src/Request.ts [hunk 1]
```diff
@@ -413,10 +413,8 @@ export class Request extends Macroable implements RequestContract {
    * The value of trustProxy is passed directly to [proxy-addr](https://www.npmjs.com/package/proxy-addr)
    */
   public protocol (): string {
-    const protocol = this.parsedUrl.protocol!
-
     if (!this._config.trustProxy(this.request.connection.remoteAddress!, 0)) {
-      return protocol
+      return 'http'
```
Comment (thetutlage) [inline src/Request.ts]: I think always returning `http` is bit weird, so we can check for `this.request.connection.encrypted` and return `https`. https://nodejs.org/dist/latest-v12.x/docs/api/tls.html#tls_tlssocket_encrypted. 

For some reason, the types of Node.js doesn't have this flag, but it does exists at runtime when using the `https` server of Node. So this is what I suggest.

1. Write a test using the `https` server
2. Ensure that protocol returns `https`, since the `encrypted` flag will be available.

Also the `encrypted` flag should get priority over everything else

**Review by thetutlage — CHANGES_REQUESTED** [review]

File: src/Request.ts (hunk 1 above)
Comment (targos) [reply src/Request.ts]: Funny, I initially implemented it with `this.request.connection.encrypted` but I wasn't able to make  a test case so I reverted the change.
If you have an idea to tell supertest to use TLS, I'll redo it.

Comment (thetutlage) [reply src/Request.ts]: `supertest` takes an instance of the http server, that means, we can pass in an instance of `https` server instance. I suggest using [pem](https://www.npmjs.com/package/pem) to generate the `secret key` and `certificate`.

#### Untested code

```ts
import { promisify } from 'util'
import { createServer: httpsServer } from 'https'
import { createCertificate } from 'pem'

const keys = await promisify(createCertificate({ days: 1, selfSigned: true }))

const server = httpsServer({
 key: keys.serviceKey,
 cert: keys.certificate,
}, function (req, res) {
  
})

supertest(server)
```

Comment (targos) [reply src/Request.ts]: I added a commit to show you the problem.
Even if I use `createServer` from `https`, supertest doesn't know that it should use TLS to connect to it. The only way I can think of would be to use a full URL for the request such as `https://localhost/` but I don't know which port number to use (supertest binds to a random port).

Comment (thetutlage) [reply src/Request.ts]: This is what I have used to run the test

```js
    process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'
    createCertificate({}, async (error, keys) => {
      if (error) {
        done(error)
        return
      }

      const server = httpsServer({ key: keys.serviceKey, cert: keys.certificate }, (req, res) => {
        const request = new Request(req, res, fakeConfig())
        res.writeHead(200, { 'content-type': 'application/json' })
        res.end(JSON.stringify({ secure: request.secure() }))
      })

      const { body } = await supertest(server).get('/')
      assert.deepEqual(body, {
        secure: false,
      })
      done()
    })
```

We have to look for `req.connection['encrypted']` instead

Comment (targos) [reply src/Request.ts]: done

**Review by thetutlage — APPROVED** [review]
